### ISSUE TITLE
[Bug]: Keyboard error

### ISSUE THREAD

**Issue by ashioyajotham** [UseHover/Stax#666] opened 2022-10-21 09:13 UTC
### Description

When trying to send through M-PESA, I try to insert the number by pressing digits on the keyboard but it doesn't work, it only works when I insert via contacts. Also worth noting, I can't delete say I made an error.

### Steps to reproduce

1. Open Stax app
2.  On homescreen, tap the send money button
3. Select destination network
4. Enter the recipient number
5. Enter the amount
6. Tap continue
7. Enter M-PESA pin

### Expected result

A confirmation message that the transaction is successful

### Actual result

No money sent since I can't get past that

### Link to screenshots/screen recordings

https://drive.google.com/file/d/13imAA4qt6Y_NDYlknVJgdC83lcN3lyP7/view?usp=sharing

### Device name

Alcatel 9003X

### Android OS

6.1

### Is your phone dual SIM or single SIM?

Single SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

victorashioya960@gmail.com

**Comment by johnswekenyi** [comment] 2022-10-21 10:39
@ashioyajotham seems like most of us are unable to reproduce this bug. I will proceed to close it for now.

**Closed by johnswekenyi** 2022-10-21 10:39 UTC
Labels: bug

**Comment by ashioyajotham** [comment] 2022-10-24 18:50
Just a by the way it is still there
